name: country_calling_code_picker_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: "https://github.com/Nostalgia3102/country_calling_code_picker_plus.git"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  device_region: ^1.4.0
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - flags/
    - raw/